### ISSUE TITLE
Label by RSS Subscription?

### ISSUE THREAD

**Issue by S1llyG1t** [ratanakvlun/deluge-labelplus#13]
Maybe I'm missing something or there is another way to accomplish what I'm trying to do.  In other clients I've been able to setup categories and assign them to particular RSS subscriptions.  I have a couple of different feeds generated from the same private tracker, so I can't just create a label from the tracker itself as they are the same.  What I'm trying to do is create labels to filter torrents by these RSS feeds so I can quickly be able to see which torrents are which in Deluge.  Any help appreciated.

**Comment by ratanakvlun** [comment]
This kinda sounds like a feed reader's job and I don't think it's a good idea to implement a feed reader in the LabelPlus plugin. Do you use a RSS plugin? If so, which? I may be able to find a way for the plugins to work with each other.

**Comment by ratanakvlun** [comment]
Closing because putting a feed reader into this plugin is out of scope.
