### ISSUE TITLE
[Bug] (User Error?) Everything in Label Settings is greyed out

### ISSUE THREAD

**Issue by Drakonas** [ratanakvlun/deluge-labelplus#15]
I have recently upgraded LabelPlus to 0.3.2.2. I am hoping I don't have to erase the entire LabelPlus database/settings files, but I am making sure this isn't a bug.

Whenever I try to open up the Label Settings for any LabelPlus label, I get this:

![LabelPlusScreenie](https://dl.dropboxusercontent.com/u/3907397/img/deluge_2016-05-01_17-01-45.png)

This even happens on new labels.

If this is a config corruption issue, let me know, and I'll backup, erase, and try again.

**Comment by ratanakvlun** [comment]
It does this when it's in read mode (reading data from the daemon). If it's stuck like that for a period of time, means that there is some sort of communications issue. Most likely the daemon is not responding.

**Comment by Drakonas** [comment]
Would having about 1100 torrents do it?

**Comment by ratanakvlun** [comment]
Could be. I find that the daemon sometimes stalls when there are lots of torrents.

**Comment by Drakonas** [comment]
I've found that while deluge is more customizable and seems to be more aggressive at speeds, it lacks in being able to handle lots of torrents.

**Comment by Drakonas** [comment]
Well it's having a timeout error, so I can't even edit label settings. :/

**Comment by Drakonas** [comment]
Closing because this is not the author's issue.
