### ISSUE TITLE
If a torrent has multiple trackers, the auto labeling for 'is not' or 'doesn't contain' does not properly evaluate

### ISSUE THREAD

**Issue by evulhotdog** [ratanakvlun/deluge-labelplus#17]
There is a tracker that uses two different domain names for its actual tracker for redundancy. 

I have a label which is set to match for any, and I added those two trackers, one on each line, which is set to 'is' and it matches/autolabels them properly. However, lets say I want to match a anything that is not a part of the few labels that I have set up. I would do 'is not' or 'doesnt contain' all of the trackers I have labels already configured for. When you try to do this, for whatever reason, the plugin doesn't properly match those particular torrents. For torrents that only have one single tracker in them, it works fine. 

I've tried to use a regex string for matching anything but, with those two trackers in the same torrent as well, but this did not yield any results.

**Comment by ratanaklun** [comment]
Just trying to understand the problem better. So you have a label that has a set of `is not`/`doesn't contain` tracker criteria using the 'match all' option and it's not matching torrents that should be matched?

**Comment by evulhotdog** [comment]
This works fine, because both are to go into the same filter, so once it matches any, it applies this tag.

![torrent1](https://cloud.githubusercontent.com/assets/365456/17459844/1889327e-5c19-11e6-9a66-048df9f4cc36.png)



@ratanaklun 

This one, does not work. In theory, this should select every single torrent that is not on either of those two trackers, but it does not. I believe this is due to the plugin not properly evaluating torrents with multiple trackers. 

![torrent2](https://cloud.githubusercontent.com/assets/365456/17459838/e0d27fde-5c18-11e6-8549-bc63c813b683.png)


P.S. This was an example, and those trackers are fake. I can provide real world examples, but I'd rather do that in private, if you need more information.

**Comment by ratanakvlun** [comment]
Fixed in commit b8eef3db.
