### ISSUE TITLE
When setting 'Stop seed at' ratio, it applies even when downloading

### ISSUE THREAD

**Issue by evulhotdog** [ratanakvlun/deluge-labelplus#18]
Back with a new issue!

So I added a torrent which had a Autolabel applied to it. As soon as the torrent is added, the torrent immediately gets paused if the setting below is configured. Shouldn't that **only** be applied after the torrent has finished downloading, and is then in the seed status? This can be an issue if you are able to seed faster than you can download as well, as the download would automatically be paused, and require manual intervention to fix/resume. 

Might be a good idea to add a check for is_status=seeding  and ratio > ratio_alotted then do xyz. 

![image](https://cloud.githubusercontent.com/assets/365456/18031640/d92a8780-6cb8-11e6-84a5-f35144da6cc9.png)

**Comment by ratanakvlun** [comment]
Not able to reproduce this using Debian 8.2, Deluge 1.3.13, and libtorrent 1.0.9.

This setting actually gets set directly in libtorrent for the torrent. If this is happening, it might be your libtorrent version.

**Comment by evulhotdog** [comment]
I updated everything, including the client to 1.3.13, and it now works properly. Thanks for the quick response, also not sure why a sub-version change would make that big a difference.
