### ISSUE TITLE
Individual label options greyed out 

### ISSUE THREAD

**Issue by s0up4200** [ratanakvlun/deluge-labelplus#26]
Hi there. 
Im running the latest LabelPlus-0.3.2.2 with Deluge 1.3.13 / libtorrent 1.0.7.0.
OS: Windows 10

I can create labels, but all options are greyed out like this. Any ideas?
![lplus](https://cloud.githubusercontent.com/assets/18177310/23480454/3cf3f2e6-fec8-11e6-95a8-61c94e905e14.jpg)

**Comment by ratanakvlun** [comment]
Probably a communications error between the GUI and the core. What does mousing over the red circle say?

**Comment by s0up4200** [comment]
You are absolutely right. Mousing over the red circle shows "Error: timed out".
I've contacted my server provider to have them take a look at it.
Thanks for your time.
