### ISSUE TITLE
Looking for an example of labelplus.conf

### ISSUE THREAD

**Issue by JohanPy** [ratanakvlun/deluge-labelplus#28]
Hello,

TL;DR:  I want to configure labelplus and create label by editing its configuration file but I need an example.

--------
I'm using Deluge on a server without graphical user interface, so I use the WebUI.
I can choose label through the WebUI but I can not create label, it's not a problem for me if I can create label by editing its configuration file.
I only label to set specific location, I'm using the label plugin but it can't move torrent if I label torrent after download.

An example would help me.

**Comment by youvegottabecrazy** [comment]
Hey @JohanPy 

Here's a sample labelplus.conf file:  https://gist.github.com/youvegottabecrazy/6e0194b36e968a0f3f068aaa960d9255

I did get this to work. I'm not clear on when the file is saved or overwritten, so it took a little playing around with starting & stopped deluge-web, enabling & disabling the plugin a few times, making sure the file wasn't overwritten, etc.

**Comment by JohanPy** [comment]
I will adapt your file, thank you for your help !
