### ISSUE TITLE
Label speed

### ISSUE THREAD

**Issue by shootingman** [ratanakvlun/deluge-labelplus#30]
Is it possible to set a group speed limit for all torrents in the same Label?

Now it just can set per torrent speed limit.

**Comment by prashker** [comment]
Per group limits (ex: 50 torrents have a combined total of X available bandwidth) would require changes to libtorrent, not this plugin. Fairly confident this is out of scope/realm of possibility, sorry.
  
See fairly old discussion here: http://forum.deluge-torrent.org/viewtopic.php?t=8055

**Comment by ratanakvlun** [comment]
This is actually already implemented in a hacky sort of way. See the "Bandwidth" tab, it's the "Shared" speed limit mode.
