### ISSUE TITLE
LabelPlus No Longer Follows Bandwidth Limits and AutoRemove

### ISSUE THREAD

**Issue by ghost** [ratanakvlun/deluge-labelplus#31]
I'm not sure when this started but my bandwidth limits and autoremove settings (at certain ratio) are no longer working. Maybe something broke with deluge version 1.3.15?

**Comment by ghost** [comment]
Using FreeBSD, Client & Server 1.3.15, and libtorrent 1.1.6.0. 

![image](https://user-images.githubusercontent.com/19519404/38471919-92ed0248-3b3d-11e8-852c-8a9429dcb093.png)


![image](https://user-images.githubusercontent.com/19519404/38471917-893ae102-3b3d-11e8-8f9b-2328afc2490c.png)




![image](https://user-images.githubusercontent.com/19519404/38471914-751cca3c-3b3d-11e8-98ba-7974484f4130.png)

**Comment by ratanakvlun** [comment]
Despite being able to set it, 0.0 is not a valid max upload speed. This is just the way Deluge or libtorrent works.
