### ISSUE TITLE
Anyway to get this compiled with Python 3.8

### ISSUE THREAD

**Issue by boivinx7** [ratanakvlun/deluge-labelplus#39]
Hi there, I had to redo my Deluge machine, so I got Ubuntu 20.04, but it has Python 3.8.
So if you have a way to compile the app in Python 3.8.
I would love too help, but im a noob in Python.
Regards

**Comment by perfect7gentleman** [comment]
It can be compiled without any errors

**Comment by ketterer** [comment]
ok how can i get the newest version and compile it for python 3.8. 
I am in the exact same boat

**Comment by perfect7gentleman** [comment]
here https://github.com/bdutro/deluge-labelplus

**Comment by dannymichel** [comment]
> here https://github.com/bdutro/deluge-labelplus

i don't think this works. it installs fine but the plugin doesn't seem to be active. i don't see any options or anything
