### ISSUE TITLE
Adding new labels

### ISSUE THREAD

**Issue by schikulski** [ratanakvlun/deluge-labelplus#6]
I might be very wrong here, but I can't see any way to create a label..? The LabelPlus column shows, but when I right click a torrent and choose LabelPlus I can only set label to "none".

![screen shot 2015-11-09 at 11 33 47](https://cloud.githubusercontent.com/assets/1258744/11031568/c38fe484-86d5-11e5-97a5-f9b8c7cd9c75.png)

**Comment by marsjaninzmarsa** [comment]
Check in LabelPlus tab in left panel.

**Comment by schikulski** [comment]
Where? Here's a screenshot of my left panel. No LabelPlus there. Running Web UI 1.3.12
![screen shot 2015-11-10 at 08 36 55](https://cloud.githubusercontent.com/assets/1258744/11056862/4b5c0a4a-8786-11e5-8dd8-aed0443476c8.png)

**Comment by ratanakvlun** [comment]
Adding labels is gtk only. You need to set up labels using the gtkui. I'd like to make the webui more complete but I haven't had the time.

**Comment by schikulski** [comment]
Aha. Get it. I'm running this on a headless server. Is there any hacky way I can add a few labels manually?

**Comment by ratanakvlun** [comment]
The easiest way would be to install the gtkui somewhere and set up the labels. Then copy over the config file. Or you can always edit the config file directly. The file is labelplus.conf and should be in your deluge user directory. There are a lot of options though. Make sure the paths are valid for the server. Format is something like this:

    {
      "file": 3, 
      "format": 1
    }{
      "prefs": {
        "options": {
          "shared_limit_interval": 10.0, 
          "reset_on_label_unset": false, 
          "move_on_changes": true, 
          "move_after_recheck": true
        }, 
        "label": {
          "max_download_speed": -1.0, 
          "move_completed_path": "/srv/share/files/Downloads/Torrents/Data", 
          "max_upload_slots": -1, 
          "prioritize_first_last": false, 
          "bandwidth_settings": false, 
          "max_connections": -1, 
          "queue_settings": false, 
          "move_completed_mode": "subfolder", 
          "autolabel_match_all": false, 
          "download_location": false, 
          "max_upload_speed": -1.0, 
          "autolabel_rules": [], 
          "download_location_path": "/srv/share/files/Downloads/Torrents/Data", 
          "auto_managed": false, 
          "autolabel_settings": false, 
          "stop_at_ratio": false, 
          "move_completed": true, 
          "download_settings": true, 
          "download_location_mode": "folder", 
          "remove_at_ratio": false, 
          "stop_ratio": 1.0, 
          "shared_limit": false
        }
      }, 
      "labels": {
        "0": {
          "name": "TV Shows", 
          "options": {
            "max_download_speed": -1.0, 
            "move_completed_path": "/srv/share/files/Downloads/Torrents/Data/TV Shows", 
            "max_upload_slots": -1, 
            "prioritize_first_last": false, 
            "bandwidth_settings": false, 
            "max_connections": -1, 
            "queue_settings": false, 
            "move_completed_mode": "subfolder", 
            "autolabel_match_all": false, 
            "download_location": false, 
            "autolabel_rules": [], 
            "max_upload_speed": -1.0, 
            "download_location_path": "/srv/share/files/Downloads/Torrents/Data", 
            "auto_managed": false, 
            "autolabel_settings": false, 
            "stop_at_ratio": false, 
            "move_completed": true, 
            "download_settings": true, 
            "download_location_mode": "folder", 
            "remove_at_ratio": false, 
            "stop_ratio": 1.0, 
            "shared_limit": false
          },
        "1": {
          "name": "Movies", 
          "options": {
            "max_download_speed": -1.0, 
            "move_completed_path": "/srv/share/files/Downloads/Torrents/Data/Movies", 
            "max_upload_slots": -1, 
            "prioritize_first_last": false, 
            "bandwidth_settings": false, 
            "max_connections": -1, 
            "queue_settings": false, 
            "move_completed_mode": "subfolder", 
            "autolabel_match_all": false, 
            "download_location": false, 
            "autolabel_rules": [], 
            "max_upload_speed": -1.0, 
            "download_location_path": "/srv/share/files/Downloads/Torrents/Data", 
            "auto_managed": false, 
            "autolabel_settings": false, 
            "stop_at_ratio": false, 
            "move_completed": true, 
            "download_settings": true, 
            "download_location_mode": "folder", 
            "remove_at_ratio": false, 
            "stop_ratio": 1.0, 
            "shared_limit": false
          }
        }
      }
    }

**Comment by ExorDG** [comment]
Aw, would love to have this support on WebUI too! I have Raspberry Pi running Raspbian Lite as a headless server too. I was excited to see this plugin and installed it only to find out that it doesn't support WebUI. Sad day for me. One can only hope. ;)

**Comment by leonroy** [comment]
Upvote for this feature, but that said GTK isn't too bad an option and it's a great way of accessing Deluge.

**Comment by spreadred** [comment]
Upvote for creating labels in WebUI as well.

**Comment by nzlorca** [comment]
Hi, 
can you help me with the config file?
I would like 3 label, Movies, series and appz.
I have this, but not working:
`
{
  "file": 3, 
  "format": 1
}{
  "prefs": {
    "options": {
      "shared_limit_interval": 10.0, 
      "reset_on_label_unset": false, 
      "move_on_changes": true, 
      "move_after_recheck": true
    }, 
    "label": {
      "max_download_speed": -1.0, 
      "move_completed_path": "/media/winyo/download/ready/apa/filmek", 
      "max_upload_slots": -1, 
      "prioritize_first_last": false, 
      "bandwidth_settings": false, 
      "max_connections": -1, 
      "queue_settings": false, 
      "move_completed_mode": "subfolder", 
      "autolabel_match_all": false, 
      "download_location": false, 
      "max_upload_speed": -1.0, 
      "autolabel_rules": [], 
      "download_location_path": "/media/winyo/download/ready/apa/filmek", 
      "auto_managed": false, 
      "autolabel_settings": false, 
      "stop_at_ratio": false, 
      "move_completed": true, 
      "download_settings": true, 
      "download_location_mode": "folder", 
      "remove_at_ratio": false, 
      "stop_ratio": 1.0, 
      "shared_limit": false
    }
  }, 
  "labels": {
    "0": {
      "name": "Sorozatok", 
      "options": {
        "max_download_speed": -1.0, 
        "move_completed_path": "/media/winyo/download/ready/apa/sorozatok", 
        "max_upload_slots": -1, 
        "prioritize_first_last": false, 
        "bandwidth_settings": false, 
        "max_connections": -1, 
        "queue_settings": false, 
        "move_completed_mode": "subfolder", 
        "autolabel_match_all": false, 
        "download_location": false, 
        "autolabel_rules": [], 
        "max_upload_speed": -1.0, 
        "download_location_path": "/media/winyo/download/downloading", 
        "auto_managed": false, 
        "autolabel_settings": false, 
        "stop_at_ratio": false, 
        "move_completed": true, 
        "download_settings": true, 
        "download_location_mode": "folder", 
        "remove_at_ratio": false, 
        "stop_ratio": 1.0, 
        "shared_limit": false
      },
    "1": {
      "name": "Flmek", 
      "options": {
        "max_download_speed": -1.0, 
        "move_completed_path": "/media/winyo/download/ready/apa/filmek", 
        "max_upload_slots": -1, 
        "prioritize_first_last": false, 
        "bandwidth_settings": false, 
        "max_connections": -1, 
        "queue_settings": false, 
        "move_completed_mode": "subfolder", 
        "autolabel_match_all": false, 
        "download_location": false, 
        "autolabel_rules": [], 
        "max_upload_speed": -1.0, 
        "download_location_path": "/media/winyo/download/downloading", 
        "auto_managed": false, 
        "autolabel_settings": false, 
        "stop_at_ratio": false, 
        "move_completed": true, 
        "download_settings": true, 
        "download_location_mode": "folder", 
        "remove_at_ratio": false, 
        "stop_ratio": 1.0, 
        "shared_limit": false
      }
    }
  }
}

`

thanks...
What is and how can I install the gtkui?
Sorry but I'm newbie ;)

thanx 
best regards

**Comment by ratanakvlun** [comment]
I think you are missing a brace at the end. gtkui is the graphical user interface that runs on gtk. It requires a desktop environment.

**Comment by nzlorca** [comment]
thanks, I will try it ;)
